services:
  dsp-fpm:
    build: .
    container_name: dsp-fpm
    working_dir: /var/www/dsp
    volumes:
      - ./:/var/www/dsp
    depends_on:
      - dsp-redis
  dsp-nginx:
    image: nginx:alpine
    container_name: dsp-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/dsp
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dsp-fpm
  dsp-redis:
    image: redis:7-alpine
    container_name: dsp-redis
    restart: always
